image: rubdos/artifact

list:
  stage: test
  script:
    art ls

check:
  stage: test
  script:
    art check

pages:
  stage: deploy
  script:
  - mkdir public
  - art export html
  - mv index.html public/
  - mv css public/
  artifacts:
    paths:
    - public
  only:
    - master
