image: rubdos/artifact

.list: &list
  stage: test
  script:
    art ls

.check: &check
  stage: test
  script:
    art check

list:
  <<: *list

check:
  <<: *check

list:master:
  <<: *list
  image: rubdos/artifact:master

check:master:
  <<: *check
  image: rubdos/artifact:master

pages:
  stage: deploy
  script:
  - mkdir -p public
  - art export html -o public
  artifacts:
    paths:
    - public
  only:
    - master
